language: python

matrix:
    include:
        - os: linux
          python: 3.7
          dist: xenial
        - os: linux
          python: 3.6
        - os: linux
          python: 3.5
        - os: osx
          language: generic
          env: TOXENV=py36
        - os: linux
          python: 3.7-dev
          dist: xenial
        - os: linux
          python: 3.8-dev
          dist: xenial
        - os: linux
          python: nightly
          dist: xenial
    allow_failures:
        - os: osx
          language: generic
          env: TOXENV=py36
install:
  - chmod +x .travis/install.sh
  - .travis/install.sh
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install --upgrade --upgrade-strategy=only-if-needed -r dev-requirements.txt --user ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --upgrade --upgrade-strategy=only-if-needed -r dev-requirements.txt ; fi
  - chmod +x .travis/test.sh
script:
  - .travis/test.sh
after_success:
  - codecov
