language: python

matrix:
    include:
        - os: linux
          python: 3.7
          dist: xenial
        - os: linux
          python: 3.6
        - os: linux
          python: 3.5
        - os: linux
          python: 3.4
        - os: linux
          python: 2.7
        - os: osx
          language: generic
          env: PYTHON=3.5.1
        - os: osx
          language: generic
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=py34
        - os: osx
          language: generic
          env: TOXENV=py27
before_install:
  - bash .travis/before_install.sh
  - python --version
install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install --upgrade --upgrade-strategy=only-if-needed -r dev-requirements.txt --user ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --upgrade --upgrade-strategy=only-if-needed -r dev-requirements.txt ; fi
  - python -m pytest pycm/ --cov=pycm --cov-report=term
  - python version_check.py
  - python -m cProfile -s cumtime pycm/pycm_profile.py
after_success:
  - codecov
