package:
  name: pycm
  version: 0.7

source:
  path: ..

build:
  noarch: python


requirements:
  build:
    - python
    - setuptools
    - codecov
    - art

  run:
    - python
about:
  home: http://pycm.shaghighi.ir
  license: MIT
  summary: pycm
